# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "rzopfli"
version = "0.1.6"
edition = "2024"
rust-version = "1.88.0"
description = "A lossless data compression tool using Zopfli"
homepage = "https://sorairolake.github.io/rzopfli/"
repository = "https://github.com/sorairolake/rzopfli"
license = "Apache-2.0 OR MIT"
keywords = ["compression", "deflate", "gzip", "zlib", "zopfli"]
categories = ["command-line-utilities", "compression"]
include = ["/LICENSES", "/README.md", "/src"]

[dependencies]
anyhow = "1.0.102"
byte-unit = "5.2.0"
clap = { version = "4.6.0", features = ["derive", "wrap_help"] }
clap_complete = "4.6.2"
clap_complete_nushell = "4.6.0"
log = "0.4.29"
simplelog = "0.12.2"
sysexits = "0.13.0"
zopfli = "0.8.3"

[dev-dependencies]
assert_cmd = "2.2.1"
flate2 = "1.1.9"
predicates = "3.1.4"
tempfile = "3.27.0"

[lints.clippy]
cargo = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[lints.rust]
missing_debug_implementations = "deny"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "forbid"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
